#!/usr/bin/env php
<?php

namespace Shimoning\ColorMeShopApi;

require_once __DIR__ . '/vendor/autoload.php';

echo __NAMESPACE__ . " shell\n";
echo "-----\nexample:\n";
echo "\$client = new Client;\n\n";
echo "// get url for OAuth\n";
echo "\$oAuthUrl = \$client->getOAuthUrl(\$options, \$scopes);\n\n";
echo "// get sales\n";
echo "\$sales = \$client->getSales();\n";

// load .env
if (\file_exists(__DIR__ . \DIRECTORY_SEPARATOR . '.env')) {
    $dotenv = \Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->load();
    echo "-----\n'.env' loaded.\n-----\n";
}

$sh = new \Psy\Shell();
$sh->addCode(sprintf("namespace %s;", __NAMESPACE__));

// set default
// - OAuth
$oAuthOptions = null;
if (!empty($_ENV['CLIENT_ID']) && !empty($_ENV['CLIENT_SECRET'])) {
    $oAuthOptions = new Entities\OAuth\Options(
        $_ENV['CLIENT_ID'],
        $_ENV['CLIENT_SECRET'],
        $_ENV['REDIRECT_URI'] ?? Constants\AuthRedirectUri::NO_REDIRECT,
    );

}
$oAuthScopes = new Values\Scopes(Constants\AuthScope::cases());

// - Access token
$token = $_ENV['TOKEN'] ?? null;

// - Client
$client = $token ?  new Client($client) : null;

$sh->setScopeVariables([
    'oAuthOptions' => $oAuthOptions,
    'oAuthScopes' => $oAuthScopes,
    'token' => $token,
    'client' => $client,
]);

$sh->run();

echo "\n-----\nBye.\n";
